import React from 'react';
import {afterEach,it,expect} from 'vitest';
import {cleanup,render,screen} from '@testing-library/react';
import {SkillCard} from '../components/skills';
import {Avatar} from '../components/avatar';
import {nodeById} from '../lib/content';
import {initialState} from '../lib/domain';
afterEach(cleanup);
for(const status of ['locked','available','in_progress','completed','mastered'])it(`exposes ${status} as text and accessible name`,()=>{render(<SkillCard node={nodeById('ten-start')!} status={status}/>);expect(screen.getByRole('link',{name:new RegExp(`Welcome to Tennis.*${status.replace('_',' ')}`,'i')})).toBeInTheDocument();});
it('renders the avatar layers in canonical order',()=>{const {container}=render(<Avatar selection={initialState().avatar}/>);expect([...container.querySelectorAll('[data-layer]')].map(e=>e.getAttribute('data-layer'))).toEqual(['shadow','body','hair-back','head','face','top','bottoms','socks','shoes','bottoms-cuff','outerwear','chin-shadow','hair-front','headwear','face-accessory','neck-accessory','back-item','held-item','foreground-effect']);});
it('doubles legacy categories and supplies the expanded wardrobe targets',async()=>{const {avatarItems}=await import('../lib/content');const targets={body:12,hair:16,hairColor:12,face:8,top:16,bottoms:10,shoes:10,accessory:18,outerwear:8,headwear:10,faceAccessory:6,backItem:8};for(const [slot,count]of Object.entries(targets))expect(avatarItems.filter(i=>i.slot===slot).length,slot).toBeGreaterThanOrEqual(count);expect(new Set(avatarItems.map(i=>i.id)).size).toBe(avatarItems.length);});
it('keeps a built-in fallback silhouette when stored assets are unknown',()=>{const {container}=render(<Avatar selection={{top:'missing-asset',hair:'missing-hair'}}/>);expect(container.querySelector('svg')).toHaveAttribute('viewBox','0 0 256 384');expect(container.querySelector('[data-layer=body] path')).toBeTruthy();expect(container.querySelector('[data-layer=top] path')).toHaveAttribute('d');});
