import {it,expect,vi,afterEach} from 'vitest';
import {initialState,stateSchema} from '../lib/domain';
import {applyCommand} from '../lib/progression';
vi.mock('../lib/supabase',()=>({supabase:{auth:{getSession:async()=>({data:{session:{access_token:'test-token'}}})}}}));
import {SupabaseProgressRepository} from '../lib/repositories/supabase';
afterEach(()=>vi.unstubAllGlobals());
it('authenticated repository retains seasonal layout avatar and window state across reads',async()=>{let stored=initialState();vi.stubGlobal('fetch',vi.fn(async(_url,options)=>{if(options.method==='POST'){const result=applyCommand(stored,JSON.parse(options.body));stored=result.state;return {ok:true,json:async()=>result};}return {ok:true,json:async()=>JSON.parse(JSON.stringify(stored))};}));const first=new SupabaseProgressRepository();await first.mutate({type:'profile',input:{themeId:'winter',animationIntensity:'off',dashboardEdge:'right',dockPosition:'top',selectedPreviewHobbyId:'swimming'}});await first.mutate({type:'avatar',slot:'outerwear',itemId:'outerwear-raincoat'});await first.mutate({type:'window',window:{appId:'settings',route:'/settings',isOpen:true,isMinimized:false,isMaximized:true,zIndex:1,x:25,y:25,width:700,height:500}});const restored=await new SupabaseProgressRepository().read();expect(restored.profile).toMatchObject({themeId:'winter',animationIntensity:'off',dashboardEdge:'right',dockPosition:'top',selectedPreviewHobbyId:'swimming',uiSchemaVersion:2});expect(restored.avatar.outerwear).toBe('outerwear-raincoat');expect(restored.windows.settings.isMaximized).toBe(true);expect(restored.ledger).toHaveLength(0);});
it('legacy UI preferences migrate with safe defaults without changing progression',()=>{const old=JSON.parse(JSON.stringify(initialState()));for(const key of ['uiSchemaVersion','themeId','animationIntensity','dashboardEdge','selectedPreviewHobbyId'])delete old.profile[key];const migrated=stateSchema.parse(old);expect(migrated.profile).toMatchObject({uiSchemaVersion:2,themeId:'spring',animationIntensity:'low',dashboardEdge:'left',selectedPreviewHobbyId:'tennis'});expect(migrated.progress).toEqual(old.progress);});
it('bringing a window up closes the one that was showing, but minimising does not',()=>{const w=(appId:'hobbies'|'character',o:Partial<{isOpen:boolean;isMinimized:boolean}>={})=>({appId,isOpen:true,isMinimized:false,isMaximized:false,zIndex:1,x:40,y:24,width:980,height:640,route:appId==='character'?'/character':'/hobbies',...o});let s=applyCommand(initialState(),{type:'window',window:w('hobbies')}).state;s=applyCommand(s,{type:'window',window:w('character')}).state;expect(s.windows.hobbies.isOpen).toBe(false);expect(s.windows.hobbies.route).toBe('/hobbies');expect(s.windows.character.isOpen).toBe(true);s=applyCommand(s,{type:'window',window:w('hobbies',{isMinimized:true})}).state;expect(s.windows.character.isOpen).toBe(true);});
