import {describe,it,expect} from 'vitest';
import {initialState,type State,type Command} from '../lib/domain';
import {applyCommand,available,hobbyLevel,lifeLevel,thresholds,done,questState,recommend,avatarUnlocked} from '../lib/progression';
import {nodes,nodeById,avatarItems} from '../lib/content';
const evidence={confirmed:true,note:'Practiced on three separate days; more consistent.',value:1000,confidence:3};
const complete=(s:State,id:string)=>applyCommand(s,{type:'complete',nodeId:id,evidence}).state;
const mark=(s:State,ids:string[])=>{for(const id of ids)s.progress[id]={status:'completed',startedAt:'2026-09-15'};return s;};
describe('level boundaries',()=>{thresholds.forEach((xp,level)=>it(`level ${level} begins at ${xp}`,()=>{expect(hobbyLevel(xp)).toBe(level);if(xp)expect(hobbyLevel(xp-1)).toBe(level-1);}));it('life level follows the specified formula',()=>{expect(lifeLevel(0)).toBe(1);expect(lifeLevel(249)).toBe(1);expect(lifeLevel(250)).toBe(2);expect(lifeLevel(1000)).toBe(3);});});
describe('prerequisites',()=>{it('enforces AND dependencies',()=>{const s=mark(initialState(),['ten-gear']);expect(available(nodeById('ten-grip')!,s)).toBe(false);mark(s,['ten-safety']);expect(available(nodeById('ten-grip')!,s)).toBe(true);});it('requires one option for each OR group as well as required prerequisites',()=>{const s=mark(initialState(),['jou-friction']);expect(available(nodeById('jou-week')!,s)).toBe(false);mark(s,['jou-gratitude']);expect(available(nodeById('jou-week')!,s)).toBe(true);});it('explicitly enforces mandatory water safety even with forged intermediate state',()=>{const s=mark(initialState(),['swi-comfort']);expect(available(nodeById('swi-float')!,s)).toBe(false);expect(()=>complete(s,'swi-float')).toThrow(/prerequisites/);});it('enforces traffic and bike-check gates',()=>{const s=mark(initialState(),['cyc-brake']);expect(()=>complete(s,'cyc-first5')).toThrow(/prerequisites/);});it('does not publish draft content',()=>{expect(available({...nodeById('ten-start')!,status:'draft'},initialState())).toBe(false);});});
describe('completion transactions',()=>{it('completes, awards an achievement, and unlocks all three first tennis branches',()=>{const r=applyCommand(initialState(),{type:'complete',nodeId:'ten-start',evidence});expect(r.xpAwarded).toBe(45);expect(r.unlockedNodeIds).toEqual(expect.arrayContaining(['ten-gear','ten-scoring','ten-safety']));expect(r.newAchievementIds).toContain('first-step');});it('is idempotent across retries',()=>{let s=complete(initialState(),'ten-start');const before=s.ledger.length;const r=applyCommand(s,{type:'complete',nodeId:'ten-start',evidence});s=r.state;expect(r.xpAwarded).toBe(0);expect(s.ledger).toHaveLength(before);});it('validates numeric evidence',()=>{const s=mark(initialState(),['jou-tools']);expect(()=>applyCommand(s,{type:'complete',nodeId:'jou-first',evidence:{...evidence,value:4}})).toThrow(/at least 5/);expect(done(complete(s,'jou-first'),'jou-first')).toBe(true);});it('requires real-world confirmation',()=>{expect(()=>applyCommand(initialState(),{type:'complete',nodeId:'ten-start',evidence:{...evidence,confirmed:false}})).toThrow(/Confirm/);});it('mastery is separate and awards only once',()=>{let s=complete(initialState(),'ten-start');s=applyCommand(s,{type:'master',nodeId:'ten-start',evidence}).state;expect(s.progress['ten-start'].status).toBe('mastered');expect(applyCommand(s,{type:'master',nodeId:'ten-start',evidence}).xpAwarded).toBe(0);});});
describe('quests and practice',()=>{it('caps weekly quest awards and permits a new week',()=>{let s=mark(initialState(),['jou-tools']);const command:Command={type:'quest',questId:'journaling-week',delta:3};s=applyCommand(s,command,new Date('2026-09-15')).state;expect(applyCommand(s,command,new Date('2026-09-16')).xpAwarded).toBe(0);expect(applyCommand(s,command,new Date('2026-09-22')).xpAwarded).toBe(60);expect(questState(s,'journaling-week',new Date('2026-09-22')).value).toBe(0);});it('allows only three active pins',()=>{let s=mark(initialState(),['ten-gear','ten-safety','cyc-check','swi-safety','jou-tools']);for(const id of ['tennis-session','cycling-checks','swimming-sessions'])s=applyCommand(s,{type:'pin',questId:id,pinned:true}).state;expect(()=>applyCommand(s,{type:'pin',questId:'journaling-week',pinned:true})).toThrow(/three/);});it('caps repeat practice XP per hobby per day and logs every unique session',()=>{let s=initialState();for(let i=0;i<3;i++)s=applyCommand(s,{type:'practice',id:crypto.randomUUID(),hobbyId:'journaling',duration:5,note:''},new Date('2026-09-15')).state;expect(s.practice).toHaveLength(3);expect(s.ledger.filter(l=>l.id.startsWith('practice:'))).toHaveLength(1);});});
describe('recommendations and rewards',()=>{it('prioritizes a started skill',()=>{const s=initialState();s.enrollments=['tennis','journaling'];s.progress['jou-start']={status:'in_progress',startedAt:''};expect(recommend(s)?.id).toBe('jou-start');});it('rotates equally ranked ignored skills after three visits',()=>{const s=initialState();s.enrollments=['tennis','journaling'];s.recommendation={id:'ten-start',visits:3};expect(recommend(s)?.id).toBe('jou-start');});it('pinned quest hobby takes priority over started content elsewhere',()=>{const s=initialState();s.enrollments=['tennis','journaling'];s.progress['ten-start']={status:'in_progress',startedAt:''};s.quests['journaling-week']={pinned:true,value:0,period:questState(s,'journaling-week').period,completed:false};expect(recommend(s)?.hobbyId).toBe('journaling');});it('unlocks cosmetics at hobby level 2',()=>{const s=initialState();const visor=avatarItems.find(a=>a.id==='visor')!;expect(avatarUnlocked(visor,s)).toBe(false);s.ledger.push({id:'test',hobbyId:'tennis',amount:300,source:'test',at:''});expect(avatarUnlocked(visor,s)).toBe(true);});it('all canonical nodes are present and have distinct lessons',()=>{expect(nodes).toHaveLength(72);expect(new Set(nodes.map(n=>n.whyItMatters)).size).toBe(72);});});

describe('full progression stress',()=>{
 it('can complete and master all 72 skills without blocked paths or duplicate rewards on retries',()=>{
  let s=initialState();s.gear['tennis-0']='owned';s.gear['tennis-1']='owned';
  const pending=new Set(nodes.map(n=>n.id));
  while(pending.size){const next=nodes.find(n=>pending.has(n.id)&&available(n,s));expect(next,'Every remaining skill must eventually unlock').toBeDefined();
   for(const type of ['start','complete','master'] as const){const command=type==='start'?{type,nodeId:next!.id}:{type,nodeId:next!.id,evidence};s=applyCommand(s,command).state;const retry=applyCommand(s,command);expect(retry.xpAwarded).toBe(0);expect(retry.state.ledger).toEqual(s.ledger);}
   pending.delete(next!.id);
  }
  expect(Object.values(s.progress).filter(p=>p.status==='mastered')).toHaveLength(72);
  expect(new Set(s.ledger.map(l=>l.id)).size).toBe(s.ledger.length);
 });
 it('preserves 100 sessions while deduplicating retries and daily XP',()=>{
  let s=initialState();const day=new Date('2026-09-16T12:00:00Z');
  for(let i=0;i<100;i++){const c:Command={type:'practice',id:crypto.randomUUID(),hobbyId:'journaling',duration:20,note:`Session ${i}`};s=applyCommand(s,c,day).state;s=applyCommand(s,c,day).state;}
  expect(s.practice).toHaveLength(100);expect(s.ledger.filter(l=>l.id.startsWith('practice:'))).toHaveLength(1);expect(s.ledger.filter(l=>l.id.startsWith('practice:')).reduce((sum,l)=>sum+l.amount,0)).toBe(20);
 });
});
