'use client';
import {useState} from 'react';
import {BodySelector} from './body-selector';
import {Avatar} from './avatar';
import {useGame} from './provider';
import {avatarItems} from '@/lib/content';
import {initialState} from '@/lib/domain';
import {avatarSlots} from '@/lib/wardrobe';
export const creationSlots=avatarSlots.filter(([slot])=>slot!=='prop');
export function CharacterCreator(){const {state,run,busy}=useGame();const [slot,setSlot]=useState('body');const options=avatarItems.filter(i=>i.slot===slot&&i.level===0&&!('achievement'in i)&&!('rewardNode'in i));const index=options.findIndex(i=>i.id===state.avatar[slot]);const equip=(i:number)=>void run({type:'avatar',slot,itemId:options[(i+options.length)%options.length].id});return <><div className="creator-layout"><div className="sprite-stage"><Avatar bodyRigId={state.profile.bodyRigId} selection={state.avatar} large/><span>PREVIEW · ALL STYLES FOR EVERYONE</span><div className="row"><button className="button" disabled={busy} onClick={()=>{const items=Object.fromEntries(creationSlots.map(([slot])=>{const choices=avatarItems.filter(i=>i.slot===slot&&i.level===0&&!('achievement'in i)&&!('rewardNode'in i));return [slot,choices[Math.floor(Math.random()*choices.length)].id];}));void run({type:'avatar-preset',items});}}>RANDOMIZE</button><button className="button" disabled={busy} onClick={()=>void run({type:'avatar-preset',items:initialState().avatar})}>RESET</button></div></div><div><BodySelector/><div role="tablist" aria-label="Character options" className="closet-tabs">{creationSlots.map(([id,label])=><button key={id} role="tab" aria-selected={slot===id} onClick={()=>setSlot(id)}>{label}</button>)}</div><div role="tabpanel" aria-label={creationSlots.find(s=>s[0]===slot)?.[1]}><div className="option-cycle"><button className="button" aria-label="Previous option" disabled={busy} onClick={()=>equip(index-1)}>◀</button><strong>{options[index]?.name||'Choose a style'}</strong><button className="button" aria-label="Next option" disabled={busy} onClick={()=>equip(index+1)}>▶</button></div><div className="closet-grid">{options.map(i=><button className="closet-item" key={i.id} aria-pressed={state.avatar[slot]===i.id} disabled={busy} onClick={()=>void run({type:'avatar',slot,itemId:i.id})}><span className="swatch" style={{background:i.color}}/>{i.name}</button>)}</div></div></div></div><div className="reward-preview"><strong>More styles unlock as your skills grow.</strong><span>▧ Tennis visor · Tennis level 2</span><span>▧ Pool goggles · Swimming level 2</span><span>▧ Journaling satchel · Journaling level 2</span></div></>;}
