'use client';
import {useState,useReducer,useEffect,useRef,type CSSProperties} from 'react';
import dynamic from 'next/dynamic';
import {characterSceneAnchor,constellationReducer} from '@/lib/home-scene';
import {HobbyConstellation} from './hobby-constellation';
import {Avatar} from './avatar';
import {useGame} from './provider';
import {Modal,XpBar} from './ui';
import {QuickStart} from './quick-start';
const CalendarWindow=dynamic(()=>import('./calendar').then(m=>m.CalendarWindow));
import {quests,nodes} from '@/lib/content';
import {lifeLevel,lifeXp,recommend,questState,hobbyLevel,hobbyXp,nodeStatus,myHobbies} from '@/lib/progression';
import type {AppId} from '@/lib/window-layout';
const SeasonalScene=dynamic(()=>import('./seasonal-scene').then(m=>m.SeasonalScene));
export function CompactLifeHud(){const {state}=useGame();const xp=lifeXp(state),level=lifeLevel(xp);return <div className="compact-life-hud" aria-label={`${state.profile.name}, Life level ${level}, ${xp} XP`}><span className="hud-name">{state.profile.name} · LVL {level}</span><span className="hud-level">LVL {level}</span><XpBar value={xp-(level-1)**2*250} max={level**2*250-(level-1)**2*250} label="Life XP"/></div>;}
export function CharacterCenteredHome({width,height,onOpen,onSave,paused=false}:{paused?:boolean;width:number;height:number;onOpen:(id:AppId,route?:string)=>void;onSave:()=>void}){
 const {state,mode,themePreview,reward,run}=useGame();const [greeting,setGreeting]=useState(false);const greeted=useRef(false);
 /** The first open of a day gets a wave and a hello; every later open stays calm. */
 useEffect(()=>{if(greeted.current)return;greeted.current=true;const today=new Date().toISOString().slice(0,10);if(state.profile.lastSeenOn!==today){setGreeting(true);setTimeout(()=>setGreeting(false),3200);}void run({type:'visit'});},[state.profile.lastSeenOn,run]);const [cheer,setCheer]=useState(false);const rewardId=reward?.id??null;
 useEffect(()=>{if(!rewardId)return;setCheer(true);const t=setTimeout(()=>setCheer(false),2600);return()=>{clearTimeout(t);setCheer(false);};},[rewardId]);const [constellation,dispatch]=useReducer(constellationReducer,{mode:'collapsed'});const expanded=constellation.mode!=='collapsed';const [plan,setPlan]=useState(false),[list,setList]=useState(false),[details,setDetails]=useState(false),[nudgeGone,setNudgeGone]=useState(false);useEffect(()=>{dispatch({type:'VIEWPORT_CHANGED'});},[width,height]);const next=recommend(state);const quest=quests.find(q=>questState(state,q.id).pinned&&!questState(state,q.id).completed);const anchor=characterSceneAnchor(width,height,state.profile.characterPosition,state.profile.dockPosition,expanded);const characterHeight=anchor.height*height,centerY=anchor.groundY*height;const character={x:width*anchor.x-characterHeight/3,y:centerY-characterHeight,width:characterHeight*2/3,height:characterHeight};const choice=themePreview||state.profile;const motionPaused=paused||state.profile.reducedMotion||choice.animationIntensity==='off';
 return <section className="character-centered-home" data-expanded={expanded} data-paused={motionPaused} aria-label="Character-centered home" style={{'--character-x':`${anchor.x*100}%`,'--character-height':`${characterHeight}px`,'--character-ground':`${centerY}px`} as CSSProperties} onKeyDown={e=>{if(e.key==='Escape'){dispatch({type:'ESCAPE'});setDetails(false);}}} onClick={e=>{if(e.target===e.currentTarget)dispatch({type:'ESCAPE'});}}>
 <SeasonalScene width={width} height={height} anchor={anchor} choice={choice} paused={motionPaused} safeZones={[character,{x:0,y:0,width,height:60},{x:0,y:height-96,width,height:96},...(expanded?[{x:0,y:64,width,height:height-160}]:[])]}/>
 {state.profile.characterSkipped&&!nudgeGone&&<div className="customize-nudge"><button className="text-button" onClick={()=>onOpen('character','/character/appearance/top')}>Your character is a placeholder — make it yours</button><button className="icon-button" aria-label="Dismiss character nudge" onClick={()=>setNudgeGone(true)}>×</button></div>}
 <div className="home-utilities"><button className="text-button" onClick={()=>setList(true)}>HOBBY PROGRESS</button><button className="text-button" onClick={()=>setPlan(true)}>PLAN A SESSION</button></div>
 {greeting&&<p className="home-greeting" role="status">{`Good to see you, ${state.profile.name}`}</p>}<div className="home-character characterStage"><button className="characterSprite" aria-label="View your hobbies" aria-expanded={expanded} onClick={()=>dispatch({type:'TOGGLE_CENTER'})}><Avatar tint={state.profile.characterTint} bodyRigId={state.profile.bodyRigId} selection={state.avatar} animation={cheer&&!motionPaused?'celebration':greeting&&!motionPaused?'gesture':'idle'} large/></button></div>
 <button className="central-progress" aria-label="Your path: view your hobbies" aria-expanded={expanded} onClick={()=>dispatch({type:'TOGGLE_CENTER'})}><span aria-hidden="true">✦</span>YOUR PATH</button>
 <HobbyConstellation value={constellation} dispatch={dispatch} width={width} height={height} character={character} onNode={(h,id)=>onOpen('hobbies',`/hobbies/${h}/nodes/${id}`)} onChoose={()=>setList(true)}/>
 <div className="home-bottom">{(()=>{const active=myHobbies(state).map(h=>({h,q:quests.find(q=>q.hobbyId===h.id)})).filter(x=>!!x.q).slice(0,3);if(!active.length)return null;return <div className="this-week" aria-label="This week">{active.map(({h,q})=>{const st=questState(state,q!.id);return <button key={h.id} onClick={()=>onOpen('hobbies',`/hobbies/${h.id}/week`)}><span>{h.icon} {h.name.split(' /')[0]}</span><small>{st.completed?'✓ done':`${st.value}/${q!.target} ${q!.unit}`}</small></button>;})}</div>;})()}<div className={`current-quest-ribbon ${details?'expanded':''}`}><button className="quest-ribbon-label" aria-expanded={details} onClick={()=>setDetails(!details)}><small>{quest?'CURRENT QUEST':next&&!next.id.endsWith('-start')?'YOUR NEXT STEP':'CHOOSE YOUR NEXT STEP'}</small><strong>{quest?quest.title:next&&!next.id.endsWith('-start')?next.title:'One small real-world action'}</strong>{quest&&<span>{questState(state,quest.id).value}/{quest.target} {quest.unit}</span>}</button>{quest?<button className="button primary" onClick={()=>onOpen('hobbies',`/hobbies/${quest!.hobbyId}`)}>CONTINUE</button>:next&&!next.id.endsWith('-start')?<button className="button primary" onClick={()=>onOpen('hobbies',`/hobbies/${next.hobbyId}/nodes/${next.id}`)}>CONTINUE</button>:<QuickStart onOpen={(h,id)=>onOpen('hobbies',`/hobbies/${h}/nodes/${id}`)}/>}{details&&<div className="quest-ribbon-details"><p>{quest?.description||next?.shortDescription||'Choose a hobby, then take your first small step.'}</p><span>{mode==='cloud'?'Cloud account':'Guest · this tab only'}</span>{mode==='demo'&&<button className="text-button" onClick={onSave}>SAVE PROGRESS</button>}</div>}</div></div>
 <Modal open={list} onClose={()=>setList(false)} title="HOBBY PROGRESS" description="All your paths, in an accessible list.">{myHobbies(state).map(h=><details key={h.id} className="hobby-progress-list"><summary>{h.icon} {h.name} · Level {hobbyLevel(hobbyXp(state,h.id))}</summary><button className="button" onClick={()=>{setList(false);onOpen('hobbies',`/hobbies/${h.id}`);}}>OPEN SKILL MAP</button>{nodes.filter(n=>n.hobbyId===h.id).map(n=><button key={n.id} className="list-progress-node" onClick={()=>{setList(false);onOpen('hobbies',`/hobbies/${h.id}/nodes/${n.id}`);}}>{n.title}<small>{nodeStatus(n,state).replace('_',' ')} · {n.xpReward} XP</small></button>)}</details>)}</Modal><Modal open={plan} onClose={()=>setPlan(false)} title="PLAN A SESSION" description="Pick a day and a hobby. Plans are gentle, never a streak."><CalendarWindow/></Modal></section>;
}
