'use client';
import {useEffect,useState,type ReactNode,type CSSProperties} from 'react';
import {PixelSprite} from './pixel-sprite';
import {usePathname,useRouter} from 'next/navigation';
import Link from 'next/link';
import {resolveWallpaper,scenes} from '@/lib/wallpapers';
import {useGame} from './provider';
import {Setup} from './onboarding/wizard';
import {cloudConfigured,supabase} from '@/lib/supabase';
/** BIOS-style boot text, typed line by line in CSS. Once per tab session, skipped by any key or tap, and
 * never shown under reduced motion or with the boot animation turned off. */
const bootLines=['GAMIFY.LIFE BIOS v0.8   (C) PERSONAL GROWTH COMPUTER','MEMORY TEST ........ 640K OK','DETECTING HOBBIES .. OK','LOADING PROFILE MODULES ....','DISCOVER · LEARN · PRACTICE · PROGRESS','JACK OF ALL TRADES, MASTER OF NONE…'];
export function BootSequence(){const {state}=useGame();const [visible,setVisible]=useState(true);useEffect(()=>{const skip=()=>{setVisible(false);sessionStorage.setItem('gamify-life:booted','true');};if(sessionStorage.getItem('gamify-life:booted')||state.profile.reducedMotion||!state.profile.bootAnimationEnabled||matchMedia('(prefers-reduced-motion: reduce)').matches){skip();return;}const timer=setTimeout(skip,1400);window.addEventListener('keydown',skip);return()=>{clearTimeout(timer);window.removeEventListener('keydown',skip);};},[state.profile.reducedMotion,state.profile.bootAnimationEnabled]);if(!visible)return null;const skip=()=>{setVisible(false);sessionStorage.setItem('gamify-life:booted','true');};return <div className="boot-sequence" onPointerDown={skip}><div className="boot-text" aria-hidden="true">{bootLines.map((line,i)=><p key={line} style={{'--chars':line.length,'--i':i} as CSSProperties}>{line}</p>)}<span className="boot-cursor"/></div><button className="boot-skip" onClick={skip}>Skip boot animation · any key</button></div>;}
export function EntryGate({children}:{children:ReactNode}){const {loaded,state,sessionActive,error}=useGame();const path=usePathname();const router=useRouter();useEffect(()=>{if(loaded&&sessionActive&&state.profile.onboardingComplete&&['/','/onboarding'].includes(path))router.replace('/home');},[loaded,sessionActive,state.profile.onboardingComplete,path,router]);const entry=!loaded||!sessionActive||!state.profile.onboardingComplete||path.startsWith('/auth/');return <><BootSequence/>{entry&&<div className="scene-wallpaper entry-wallpaper" aria-hidden="true" style={{background:scenes[resolveWallpaper(state.profile.wallpaper,state.profile.themeId)].prev}}/>/* the scene's gradient: pixi.js loads only where the desktop shows (brief §5) */}{!loaded?<div className="entry-screen"><p role="status" className="px-loading"><PixelSprite name="hourglass" size={24}/>Opening your computer…</p></div>:path.startsWith('/auth/')?children:!sessionActive?<LoginDialog/>:!state.profile.onboardingComplete?<Setup/>:children}{error&&!sessionActive&&<p role="alert" className="inline-error">{error}</p>}</>;}
/** A little colour on the way in: drifting pixel motes behind the login panel. Decorative only —
 * hidden from screen readers, and still under reduced motion. */
const motes=[[4,16,0,'#D58E8A'],[9,54,1.4,'#D0AE5C'],[5,82,2.8,'#70AFA5'],[14,30,0.7,'#A996C5'],[3,68,2.1,'#8DA876'],[12,92,3.5,'#D58E8A'],[88,20,1.1,'#D2B95B'],[93,58,2.4,'#70AFA5'],[85,86,0.3,'#A996C5'],[96,36,3.1,'#8DA876'],[90,72,1.8,'#D0AE5C'],[82,48,2.6,'#D58E8A'],[34,6,1.2,'#70AFA5'],[62,8,2.9,'#D2B95B'],[47,95,0.9,'#A996C5'],[26,97,2.2,'#8DA876']] as const;
export function EntrySparkle(){return <div className="entry-sparkle" aria-hidden="true">{motes.map(([left,top,delay,color])=><i key={`${left}-${top}`} style={{left:`${left}%`,top:`${top}%`,background:color,animationDelay:`${delay}s`}}/>)}</div>;}
export function LoginDialog(){const {demo}=useGame();const [guest,setGuest]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);return <div className="entry-screen"><EntrySparkle/><div className="login-dialog mac-window"><div className="titlebar"><PixelSprite name="quests" size={20}/><h1>WELCOME TO GAMIFY.LIFE</h1></div><div className="window-pad"><div className="login-emblem" aria-hidden="true"><PixelSprite name="pc-building" size={64}/><span>YOUR NEXT CHAPTER</span></div>{cloudConfigured?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');const fd=new FormData(e.currentTarget);try{const {error}=await supabase!.auth.signInWithPassword({email:String(fd.get('email')),password:String(fd.get('password'))});if(error)setMessage(error.message);}catch{setMessage('Unable to connect. Please try again.');}finally{setBusy(false);}}}><label className="field">Email / username<input name="email" type="email" autoComplete="username" required/></label><label className="field">Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="button primary full" disabled={busy}>{busy?'CONNECTING…':'LOG IN'}</button></form>:<><p>Welcome to your personal growth computer.</p><button className="button primary full" onClick={()=>setMessage('Cloud login is not configured yet. Guest mode includes every ordinary feature.')}>LOG IN</button></>}{message&&<p role="status" className="inline-error">{message}</p>}<button className="button full" onClick={()=>setGuest(true)}>CONTINUE AS GUEST</button>{guest&&<div className="guest-notice" role="note"><p>Guest progress disappears when this session ends. Create an account anytime to save your character and progress.</p><button className="button primary full" onClick={()=>void demo()}>BEGIN GUEST SESSION</button></div>}<Link className="text-button" href="/auth/sign-up">CREATE PROFILE</Link><p className="metadata">Accounts save to the cloud when connected. Guests use this tab only.</p></div></div><p className="entry-signature">JACK OF ALL TRADES, MASTER OF NONE, BUT OFTENTIMES BETTER THAN A MASTER OF ONE</p></div>;}
