'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import Link from 'next/link';
import {useGame} from './provider';
import {randomTint} from '@/lib/tints';
import {CharacterCreator} from './character-creator';
import {hobbies,hobbyIds} from '@/lib/content';
import {cloudConfigured,supabase} from '@/lib/supabase';
export function BootSequence(){const {state}=useGame();const [visible,setVisible]=useState(true);useEffect(()=>{const skip=()=>{setVisible(false);sessionStorage.setItem('gamify-life:booted','true');};if(sessionStorage.getItem('gamify-life:booted')||state.profile.reducedMotion||!state.profile.bootAnimationEnabled||matchMedia('(prefers-reduced-motion: reduce)').matches){skip();return;}const timer=setTimeout(skip,1400);const key=(e:KeyboardEvent)=>{if(e.key==='Enter'||e.key==='Escape')skip();};window.addEventListener('keydown',key);return()=>{clearTimeout(timer);window.removeEventListener('keydown',key);};},[state.profile.reducedMotion,state.profile.bootAnimationEnabled]);if(!visible)return null;return <button className="boot-sequence" onClick={()=>{setVisible(false);sessionStorage.setItem('gamify-life:booted','true');}} aria-label="Skip boot animation"><span className="boot-symbol">▣</span><strong>GAMIFY.LIFE OS</strong><span>LOADING PROFILE MODULES…</span><span className="boot-progress">■ ■ ■ ■ □ □</span><small>DISCOVER · LEARN · PRACTICE · PROGRESS</small><small>Click or press Enter to skip</small></button>;}
export function EntryGate({children}:{children:ReactNode}){const {loaded,state,sessionActive,error}=useGame();const path=usePathname();const router=useRouter();useEffect(()=>{if(loaded&&sessionActive&&state.profile.onboardingComplete&&['/','/onboarding'].includes(path))router.replace('/home');},[loaded,sessionActive,state.profile.onboardingComplete,path,router]);return <><BootSequence/>{!loaded?<div className="entry-screen"><p role="status">Opening your computer…</p></div>:path.startsWith('/auth/')?children:!sessionActive?<LoginDialog/>:!state.profile.onboardingComplete?<Setup/>:children}{error&&!sessionActive&&<p role="alert" className="inline-error">{error}</p>}</>;}
export function LoginDialog(){const {demo}=useGame();const [guest,setGuest]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);return <div className="entry-screen"><div className="login-dialog mac-window"><div className="titlebar"><h1>WELCOME TO GAMIFY.LIFE</h1></div><div className="window-pad"><div className="login-emblem" aria-hidden="true">▣<span>YOUR NEXT CHAPTER</span></div>{cloudConfigured?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');const fd=new FormData(e.currentTarget);try{const {error}=await supabase!.auth.signInWithPassword({email:String(fd.get('email')),password:String(fd.get('password'))});if(error)setMessage(error.message);}catch{setMessage('Unable to connect. Please try again.');}finally{setBusy(false);}}}><label className="field">Email / username<input name="email" type="email" autoComplete="username" required/></label><label className="field">Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="button primary full" disabled={busy}>{busy?'CONNECTING…':'LOG IN'}</button></form>:<><p>Welcome to your personal growth computer.</p><button className="button primary full" onClick={()=>setMessage('Cloud login is not configured yet. Guest mode includes every ordinary feature.')}>LOG IN</button></>}{message&&<p role="status" className="inline-error">{message}</p>}<button className="button full" onClick={()=>setGuest(true)}>CONTINUE AS GUEST</button>{guest&&<div className="guest-notice" role="note"><p>Guest progress disappears when this session ends. Create an account anytime to save your character and progress.</p><button className="button primary full" onClick={()=>void demo()}>BEGIN GUEST SESSION</button></div>}<Link className="text-button" href="/auth/sign-up">CREATE PROFILE</Link><p className="metadata">Accounts save to the cloud when connected. Guests use this tab only.</p></div></div><p className="entry-signature">A COZY HOBBY RPG · ONE REAL STEP AT A TIME</p></div>;}
function Setup(){const {state,run,busy,error}=useGame();const router=useRouter();const [name,setName]=useState(state.profile.name);const [selected,setSelected]=useState<string[]>(state.enrollments);const [back,setBack]=useState(false);const character=state.profile.characterCreated&&!back;return <div className="entry-screen setup-screen"><section className="mac-window setup-window"><div className="titlebar"><h1>{character?'CHOOSE YOUR PATH':'CHARACTER SETUP'}</h1><span>{character?'2':'1'} / 2</span></div><div className="window-pad">{error&&<p className="inline-error" role="alert">{error}</p>}{!character?<><label className="field">Character name<input value={name} maxLength={40} onChange={e=>setName(e.target.value)}/></label><CharacterCreator/><button className="button primary full" disabled={busy||!name.trim()} onClick={async()=>{if(await run({type:'profile',input:{name,characterCreated:true}}))setBack(false);}}>CREATE CHARACTER</button><button className="button full" disabled={busy} onClick={async()=>{if(await run({type:'profile',input:{name:name.trim()||'Player',characterCreated:true,characterSkipped:true,characterTint:randomTint()}}))setBack(false);}}>SKIP FOR NOW</button><p className="metadata center">We’ll give you a placeholder. You can design your character any time from the Character app.</p></>:<><h2>A little curiosity goes a long way.</h2><p>You can add or pause hobbies later.</p><div className="onboarding-choices">{hobbies.map(h=><button key={h.id} className={selected.includes(h.id)?'selected':''} aria-pressed={selected.includes(h.id)} onClick={()=>setSelected(old=>old.includes(h.id)?old.filter(x=>x!==h.id):[...old,h.id])}><span>{h.icon}</span><strong>{h.name}</strong><small>{h.description}</small><small>{h.startSummary}</small></button>)}</div><button className="button primary" disabled={busy||!selected.length} onClick={async()=>{if(!await run({type:'enroll',hobbyIds:selected as typeof hobbyIds[number][]}))return;if(await run({type:'profile',input:{onboardingComplete:true}}))router.push('/home');}}>OPEN MY DESKTOP</button><button className="button" onClick={()=>setBack(true)}>BACK TO CHARACTER</button></>}</div></section></div>;}
