'use client';
import {PixelSprite} from './pixel-sprite';
import {useState,useEffect,useRef,type CSSProperties} from 'react';
import {hobbies,nodes,nodeById} from '@/lib/content';
import {done,available,nodeStatus,hobbyLevel,hobbyXp,thresholds,unmet} from '@/lib/progression';
import {constellationLayout,type ConstellationState,type ConstellationEvent,type Rect} from '@/lib/home-scene';
import {useGame} from './provider';
export function HobbyConstellation({value,dispatch,width,height,character,hub,onNode,onChoose}:{value:ConstellationState;dispatch:(e:ConstellationEvent)=>void;width:number;height:number;character:Rect;hub?:Rect;onNode:(hobby:string,id:string)=>void;onChoose:()=>void}){
 const {state,run}=useGame();const [focus,setFocus]=useState<string|null>(null);const active=hobbies.filter(h=>state.enrollments.includes(h.id as typeof state.enrollments[number]));const selected=value.mode==='progress'?value.hobbyId:null;const hn=nodes.filter(n=>n.hobbyId===selected),previous=hn.filter(n=>done(state,n.id)).at(-1),current=hn.find(n=>state.progress[n.id]?.status==='in_progress')||hn.find(n=>available(n,state));const near=hn.filter(n=>available(n,state)&&n!==current).slice(0,2),locked=hn.find(n=>nodeStatus(n,state)==='locked');const preview=[...new Map([previous,current,...near,locked].filter(n=>!!n).map(n=>[n.id,n])).values()].slice(0,width<1200?3:5);const layout=constellationLayout(width,height,character,active.length,selected?preview.length:0,hub);const progressRef=useRef<HTMLElement|null>(null);useEffect(()=>{setFocus(null);},[selected]);useEffect(()=>{if(selected&&layout.mode==='strip')progressRef.current?.scrollIntoView({behavior:state.profile.reducedMotion?'auto':'smooth',block:'nearest',inline:'nearest'});},[selected,layout.mode,state.profile.reducedMotion]);const inspected=nodes.find(n=>n.id===focus);if(value.mode==='collapsed')return null;
 const geometry=(index:number)=>layout.mode==='spatial'?{left:layout.placements[index].x,top:layout.placements[index].y,width:layout.placements[index].width,height:layout.placements[index].height,'--reveal-order':index} as CSSProperties:{'--reveal-order':index} as CSSProperties;
 return <div className={`hobby-constellation constellation-${layout.mode}`} data-mode={value.mode} data-layout={layout.mode} aria-label="Hobby constellation">
 {layout.mode==='spatial'&&<svg className="pixel-connectors" width={width} height={height} aria-hidden="true"><defs><mask id="constellation-character-mask"><rect width="100%" height="100%" fill="white"/><rect {...character} x={character.x-8} y={character.y-8} width={character.width+16} height={character.height+16} fill="black"/></mask></defs><g mask="url(#constellation-character-mask)">{layout.placements.map((r,i)=><path key={i} d={`M${layout.center.x} ${layout.center.y}H${Math.round((layout.center.x+r.x+r.width/2)/2)}V${r.y+r.height/2}H${r.x+r.width/2}`} style={{'--reveal-order':i} as CSSProperties}/>)}</g></svg>}
 <nav className="constellation-hobbies" aria-label="Active hobbies">{active.map((h,i)=>{const xp=hobbyXp(state,h.id),level=hobbyLevel(xp),progress=Math.min(1,(xp-thresholds[level])/((thresholds[level+1]||xp+500)-thresholds[level]));return <button className="hobby-branch-node" key={h.id} style={{...geometry(i),'--hobby':h.color} as CSSProperties} aria-pressed={selected===h.id} onClick={()=>{dispatch({type:'SELECT_HOBBY',hobbyId:h.id as typeof state.enrollments[number]});void run({type:'profile',input:{selectedPreviewHobbyId:h.id as typeof state.enrollments[number]}});}}><span className="hobby-progress-ring" style={{'--ring':`${progress*100}%`} as CSSProperties} aria-hidden="true"><PixelSprite name={h.id} size={16}/></span><strong>{h.name.split(' /')[0]}</strong><small>LVL {level} · {xp} XP</small></button>;})}{!active.length&&<button className="button" onClick={onChoose}>CHOOSE A HOBBY</button>}</nav>
 {selected&&<nav ref={progressRef} className="constellation-progress" aria-label={`${selected} nearby skills`}>{preview.map((n,i)=>{const status=nodeStatus(n,state);return <button key={n.id} className={`progress-branch-node ${status}`} style={geometry(active.length+i)} onFocus={()=>setFocus(n.id)} onPointerEnter={()=>setFocus(n.id)} aria-label={`${n.title}, ${status.replace('_',' ')}, open node`} onClick={()=>{dispatch({type:'SELECT_PROGRESS_NODE'});onNode(n.hobbyId,n.id);}}><span aria-hidden="true">{({available:'◇',in_progress:'◷',completed:'✓',mastered:'☆',locked:'▧'})[status]}</span><strong>{n.title}</strong><small>{status.replace('_',' ')}{!done(state,n.id)?` · ${n.xpReward} XP`:''}</small></button>;})}</nav>}
 {inspected&&<div className="constellation-inspector" role="status"><strong>{inspected.title} · OPEN NODE ↗</strong><span>{nodeStatus(inspected,state)==='locked'?`First complete: ${unmet(inspected,state).map(id=>nodeById(id)?.title).join(', ')}`:inspected.shortDescription}</span></div>}</div>;
}
