'use client';
import {useState} from 'react';
import {firstQuests,type QuickHobby} from '@/lib/quick-start';
import {hobbies,nodeById,gear} from '@/lib/content';
import {useGame} from './provider';
import {Modal} from './ui';
export function FirstQuestSummary({hobbyId}:{hobbyId:QuickHobby}){const q=firstQuests[hobbyId],node=nodeById(q.nodeId)!;return <div className="first-quest-summary"><div className="first-quest-facts"><section><h3>YOU NEED</h3><ul>{q.need.map(n=><li key={n}>{n}</li>)}</ul></section><section><h3>TIME TO START</h3><p>About {q.minutes} minutes</p><span className="xp-pill">+{node.xpReward} XP for your starting goal</span></section></div><h3>DO THIS FIRST</h3><p>{q.action}</p><aside className="first-safety"><strong>SAFETY</strong> {q.safety}</aside></div>;}
export function FirstQuestDetails({hobbyId}:{hobbyId:QuickHobby}){const q=firstQuests[hobbyId],node=nodeById(q.nodeId)!;return <details className="first-quest-details"><summary>MORE DETAILS</summary><details><summary>What to buy</summary><p>{q.cost}. Borrow first; avoid premium upgrades until you know what helps you.</p>{gear.filter(g=>g.hobbyId===hobbyId&&g.necessity==='required').map(g=><p key={g.id}><strong>{g.name}:</strong> {g.guidance}</p>)}</details><details><summary>Rules & safety</summary><p>{q.safety}</p>{node.safetyNotes.map(n=><p key={n}>{n}</p>)}</details><details><summary>How to do it</summary><ol>{node.instructions.map(n=><li key={n}>{n}</li>)}</ol></details><details><summary>Common mistakes</summary>{node.commonMistakes.map(n=><p key={n}>{n}</p>)}</details><details><summary>Resources</summary>{node.resources.map(r=><p key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a></p>)}<small>General references; lesson content is still a curated draft.</small></details></details>;}
export function QuickStart({onOpen,initialHobby}:{onOpen:(hobby:QuickHobby,nodeId:string)=>void;initialHobby?:QuickHobby}){const {state,run,busy}=useGame();const [open,setOpen]=useState(false),[choice,setChoice]=useState<QuickHobby|null>(null);return <><button className="button primary quick-start-trigger" onClick={()=>{setChoice(initialHobby||null);setOpen(true);}}>GET STARTED</button><Modal open={open} onClose={()=>setOpen(false)} title={choice?`${firstQuests[choice].name.toUpperCase()} — FIRST QUEST`:'CHOOSE YOUR FIRST QUEST'} description={choice?'One small action. Use what you have.':'Choose something you’re curious about.'}>{choice?<><FirstQuestSummary hobbyId={choice}/><button className="button primary full" disabled={busy} onClick={async()=>{const q=firstQuests[choice];if(!state.enrollments.includes(choice)&&!await run({type:'enroll',hobbyIds:[choice]}))return;if(!await run({type:'start',nodeId:q.nodeId}))return;setOpen(false);onOpen(choice,q.nodeId);}}>START QUEST</button><FirstQuestDetails hobbyId={choice}/><button className="text-button" onClick={()=>setChoice(null)}>CHOOSE ANOTHER HOBBY</button></>:<div className="quick-choices">{Object.entries(firstQuests).sort(([a],[b])=>Number(state.enrollments.includes(b as QuickHobby))-Number(state.enrollments.includes(a as QuickHobby))).map(([id,q])=><button key={id} className="quick-choice" data-enrolled={state.enrollments.includes(id as QuickHobby)} onClick={()=>setChoice(id as QuickHobby)}><span aria-hidden="true">{hobbies.find(h=>h.id===id)?.icon}</span><strong>{state.enrollments.includes(id as QuickHobby)?'CONTINUE ':''}{q.name.toUpperCase()}</strong><p>{q.description}</p><small>{q.minutes} MIN · {q.cost}</small></button>)}</div>}</Modal></>;}
