'use client';
import {useEffect,useId,useState,type CSSProperties} from 'react';
import type {Rect,SceneAnchor} from '@/lib/home-scene';
import {seasonalThemes,type ThemeChoice} from '@/lib/themes';
/** Original pixel geometry is redrawn on a four-pixel grid; no scaled landscape bitmap. */
export function SeasonalScene({width,height,anchor,safeZones,choice,paused=false}:{width:number;height:number;anchor:SceneAnchor;safeZones:Rect[];choice:ThemeChoice;paused?:boolean}){
 const mask=useId().replaceAll(':','');const [hidden,setHidden]=useState(false);useEffect(()=>{const update=()=>setHidden(document.hidden);update();document.addEventListener('visibilitychange',update);return()=>document.removeEventListener('visibilitychange',update);},[]);
 const theme=seasonalThemes.find(t=>t.id===choice.themeId)!;const winter=theme.id==='winter',fall=theme.id==='fall',summer=theme.id==='summer';const q=(n:number)=>Math.round(n/4)*4,x=q(width*anchor.x),horizon=q(height*.35),ground=q(height*anchor.groundY),half=q(Math.min(width*.22,180));const count=choice.animationIntensity==='off'?0:theme.animationLayers[choice.animationIntensity];const pathColor=winter?'#dbe2e3':fall?'#c59768':summer?'#d3c9a2':'#c8c4a0';
 function boundary(sign:number){return Array.from({length:12},(_,i)=>{const t=i/11,y=q(horizon+(height-horizon)*t),extent=q(12+half*t);return `${i?'L':'M'}${x+sign*extent} ${y}${i<11?`V${q(horizon+(height-horizon)*(i+1)/11)}`:''}`;}).join('');}
 return <svg className="anchored-seasonal-scene" data-season={theme.id} data-composition={width<640?'portrait':'landscape'} data-anchor-x={x} data-paused={paused||hidden} data-intensity={choice.animationIntensity} width="100%" height="100%" viewBox={`0 0 ${width} ${height}`} shapeRendering="crispEdges" aria-hidden="true">
 <defs><mask id={mask}><rect width={width} height={height} fill="white"/>{safeZones.map((r,i)=><rect key={i} x={r.x-12} y={r.y-12} width={r.width+24} height={r.height+24} fill="black"/>)}</mask></defs>
 <g data-scene-layer="sky"><rect width={width} height={height} fill={theme.palette.sky}/><path d={`M${q(width*.76)} 48h32v8h8v24h-8v8h-32v-8h-8V56h8z`} fill={winter?'#e6e4d6':'#f2dfad'}/></g>
 <g data-scene-layer="distant" fill={winter?'#829298':fall?'#a89570':summer?'#7fa0a0':'#9aae97'}>{Array.from({length:Math.ceil(width/96)},(_,i)=><path key={i} d={`M${i*96} ${horizon}v-32h16v-16h24v-16h24v32h16v16h16v16z`}/>)}</g>
 <g data-scene-layer="ground"><rect y={horizon} width={width} height={height-horizon} fill={winter?'#bfcdd1':fall?'#8f9869':summer?'#95b3a5':'#a9bb91'}/>{summer&&<path d={`M0 ${horizon}H${width}v64H0z`} fill="#8db7bc"/>}<path data-scene-layer="perspective" data-vanishing-x={x} d={`${boundary(-1)}L${x+half} ${height}${Array.from({length:12},(_,i)=>{const t=(11-i)/11;return `L${x+q(12+half*t)} ${q(horizon+(height-horizon)*t)}`;}).join('')}Z`} fill={pathColor}/><path d={boundary(-1)} fill="none" stroke={winter?'#aabdc4':'#aa9977'} strokeWidth="4"/><path d={boundary(1)} fill="none" stroke={winter?'#f0efdf':'#ddd0a2'} strokeWidth="4"/></g>
 <g data-scene-layer="midground">{[-1,1].map(sign=>{const space=sign<0?x:width-x;const outer=sign<0?0:width;const w=q(Math.min(160,space*.38)),px=sign<0?outer:outer-w;return winter?<g key={sign}><path d={`M${px} ${horizon-96}h${w}v${height-horizon+96}h${-w}z`} fill={sign<0?'#687888':'#788490'}/><path d={`M${px} ${horizon-104}h${w}v8h${-w}z`} fill="#e6e7dc"/>{Array.from({length:8},(_,i)=><rect key={i} x={px+12+i%2*Math.max(24,w-40)} y={horizon-72+Math.floor(i/2)*40} width="16" height="24" fill={i%3?'#dbc796':'#9eaeb1'}/>)}</g>:<g key={sign}><path d={`M${px+w/2-8} ${horizon-12}h16v${Math.max(80,ground-horizon)}h-16z`} fill="#71624d"/><path d={`M${px} ${horizon-56}h${w}v72h-12v24h${-w+24}v-24h-12z`} fill={fall?(sign<0?'#ac7657':'#ba885a'):summer?'#739278':'#83a178'}/><path d={`M${px+12} ${horizon-68}h${w-24}v28h${-w+24}z`} fill={fall?'#ca9a64':'#9bb183'}/><path d={`M${px+20} ${horizon-32}h16v8h-16zM${px+w-36} ${horizon+8}h20v8h-20z`} fill={fall?'#dfb879':'#b4c393'}/></g>;})}</g>
 <g data-scene-layer="foreground" mask={`url(#${mask})`}>{Array.from({length:width<640?10:24},(_,i)=>{const px=q((i*137+21)%width),py=q(ground+30+(i*41)%Math.max(1,height-ground-30));return <path key={i} d={`M${px} ${py}h8v4h4v4h-12z`} fill={winter?'#e7ebe5':fall?['#b57752','#d0a05e','#9e6d4e'][i%3]:summer?'#758c75':['#d4b2b1','#e2d5ac','#88a276'][i%3]}/>;})}</g>
 <g data-scene-layer="ambient" mask={`url(#${mask})`}>{Array.from({length:count},(_,i)=><g key={i} className="scene-particle" style={{'--drift':`${summer?8:24+i%3*12}px`,'--fall':`${summer?0:50+i%5*12}px`,'--duration':`${12+i%5*3}s`,'--delay':`${-i*3.7}s`} as CSSProperties}><path d={`M${q((i*179+38)%width)} ${q((i*89+53)%height)}h${winter?4:8}v4h-4v4h-4z`} fill={winter?'#f3f2e6':fall?'#d6a465':summer?'#d3e6d4':'#e3c8bb'}/></g>)}</g></svg>;
}
