'use client';
import {useEffect,type ReactNode,type CSSProperties} from 'react';
import {useGame} from './provider';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import {PixelSprite} from './pixel-sprite';
export function Window({title,children,className='',label,action}:{title:string;children:ReactNode;className?:string;label?:string;action?:ReactNode}){return <section className={`mac-window ${className}`} aria-label={label||title}><div className="titlebar"><span className="window-square" aria-hidden="true"/><h2>{title}</h2><span className="title-stripes"/>{action}</div>{children}</section>;}
export function XpBar({value,max,color='#819776',label='XP'}:{value:number;max:number;color?:string;label?:string}){return <div className="xp-track" role="progressbar" aria-label={label} aria-valuenow={value} aria-valuemin={0} aria-valuemax={Math.max(value,max)}><div style={{width:`${Math.min(100,value/max*100)}%`,'--bar-color':color} as CSSProperties}/></div>;}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description:string;children:ReactNode}){const {error,clearError}=useGame();useEffect(()=>{if(open)clearError();},[open,clearError]);return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal mac-window"><div className="titlebar"><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="icon-button" aria-label="Close dialog"><PixelSprite name="close" size={20}/></Dialog.Close></div><div className="modal-body"><Dialog.Description className="muted">{description}</Dialog.Description>{error&&<div className="inline-error" role="alert">{error}</div>}{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){return <header className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</header>;}
export function Empty({children,href,label}:{children:ReactNode;href?:string;label?:string}){return <div className="empty"><span className="empty-symbol" aria-hidden="true">✧</span><p>{children}</p>{href&&<Link className="button small" href={href}>{label}</Link>}</div>;}
