import type {hobbyIds} from './content';
export type HobbyId=typeof hobbyIds[number];
export type ConstellationState={mode:'collapsed'}|{mode:'hobbies'}|{mode:'progress';hobbyId:HobbyId};
export type ConstellationEvent={type:'TOGGLE_CENTER'}|{type:'SELECT_HOBBY';hobbyId:HobbyId}|{type:'SELECT_PROGRESS_NODE'}|{type:'CLICK_OUTSIDE'}|{type:'ESCAPE'}|{type:'VIEWPORT_CHANGED'};
export function constellationReducer(state:ConstellationState,event:ConstellationEvent):ConstellationState{switch(event.type){case'TOGGLE_CENTER':return state.mode==='collapsed'?{mode:'hobbies'}:{mode:'collapsed'};case'SELECT_HOBBY':return {mode:'progress',hobbyId:event.hobbyId};case'CLICK_OUTSIDE':case'ESCAPE':case'SELECT_PROGRESS_NODE':return {mode:'collapsed'};case'VIEWPORT_CHANGED':return state;}}
export type Rect={x:number;y:number;width:number;height:number};
export type Point={x:number;y:number};
export function intersects(a:Rect,b:Rect,pad=0){return a.x<b.x+b.width+pad&&a.x+a.width+pad>b.x&&a.y<b.y+b.height+pad&&a.y+a.height+pad>b.y;}
/** Score source-relative candidates, reject unsafe rectangles, then reserve each placement.
 * No viewport-specific coordinate table; cramped scenes use the same scrollable strip. */
export function constellationLayout(width:number,height:number,character:Rect,count:number,progressCount=0){const safe={x:16,y:66,width:width-32,height:height-164};const center={x:character.x+character.width/2,y:character.y+character.height+26};const reserved:Rect[]=[{...character,x:character.x-16,width:character.width+32},{x:center.x-72,y:center.y-28,width:144,height:58}];const placements:Rect[]=[];const size={width:progressCount?142:132,height:76};if(width<900)return {mode:'strip' as const,placements,center};for(let i=0;i<count+progressCount;i++){const candidates=[];for(const radius of [width*.19,width*.29,width*.4])for(let step=0;step<24;step++){const angle=step*Math.PI/12;const p={x:Math.round(center.x+Math.cos(angle)*radius-size.width/2),y:Math.round(character.y+character.height*.5+Math.sin(angle)*Math.min(radius,height*.31)-size.height/2),...size};if(p.x<safe.x||p.y<safe.y||p.x+p.width>safe.x+safe.width||p.y+p.height>safe.y+safe.height||reserved.some(r=>intersects(r,p,12)))continue;const edge=Math.min(p.x-safe.x,safe.x+safe.width-p.x-p.width,p.y-safe.y,safe.y+safe.height-p.y-p.height);const clearance=placements.length?Math.min(...placements.map(r=>Math.hypot(r.x-p.x,r.y-p.y))):80;candidates.push({p,score:edge*.15+Math.min(clearance,250)-Math.abs(radius-width*.24)*.1});}candidates.sort((a,b)=>b.score-a.score);if(!candidates.length)return {mode:'strip' as const,placements:[],center};placements.push(candidates[0].p);reserved.push(candidates[0].p);}return {mode:'spatial' as const,placements,center};}
export type CharacterScenePosition='left'|'center'|'right'|'auto';
export type SceneAnchor={x:number;groundY:number;facing:'front';width:number;height:number};
export function characterSceneAnchor(width:number,height:number,position:CharacterScenePosition,dock:string,expanded=false):SceneAnchor{const compact=width<900;const h=expanded&&compact?140:Math.max(140,Math.min(520,height*.52,height-170));const ground=expanded&&compact?Math.max(160,Math.min(height-240,240)):Math.max(h+55,height*.62);return {x:compact?.5:position==='left'?.32:position==='right'?.68:position==='auto'?(dock==='left'?.56:dock==='right'?.44:.5):.5,groundY:ground/height,facing:'front',width:h*2/3/width,height:h/height};}
