import type {hobbyIds} from './content';
type HobbyId=typeof hobbyIds[number];
export const firstQuests={
 tennis:{name:'Tennis',nodeId:'ten-start',description:'Build a little confidence on court.',minutes:20,need:['Borrowed racket and a few balls','Safe shoes; wall or court access'],action:'After the safety steps, learn ready position and make 20 controlled self-drop contacts.',safety:'Check the court, warm up, keep clear of others, and stop if you feel pain. Complete Court Safety before logging practice.',cost:'USE WHAT YOU OWN'},
 cycling:{name:'Cycling',nodeId:'cyc-start',description:'Get comfortable starting and stopping.',minutes:15,need:['Working bike with functional brakes','Properly fitted helmet'],action:'Complete the ABC check, then practice five smooth starts and stops in a safe area.',safety:'Finish the bike-check and safety steps before riding. Road use needs a functional front brake, including fixed gear.',cost:'HELMET: BUY IT NEW'},
 swimming:{name:'Swimming',nodeId:'swi-start',description:'Find calm, supervised time in the water.',minutes:20,need:['Supervised pool access','Safe swimwear; goggles optional'],action:'Review water safety, then practice relaxed exhaling in shallow water with qualified supervision.',safety:'Never swim alone or try breath-holding contests. Complete Water Safety before drills or practice logs.',cost:'POOL ACCESS REQUIRED'},
 journaling:{name:'Journaling',nodeId:'jou-start',description:'Make room for a few words.',minutes:5,need:['Any paper or notebook','Any pen you already own'],action:'Write continuously for five minutes. No formatting, perfect sentences, or special notebook required.',safety:'Choose a private place for personal writing; share only what you want to share. Complete the tools step before logging practice.',cost:'USE WHAT YOU OWN'}
,
 'pc-building':{name:'PC Building',nodeId:'pcb-start',description:'Know the parts before you touch them.',minutes:15,need:['Somewhere hard and non-carpeted to work','A single Phillips screwdriver'],action:'Read what each part does, then write down what the machine is for and roughly what you can spend.',safety:'Unplug at the wall and hold the power button before opening anything. Ground yourself on the bare case, and never open a power supply. Complete Electrical and ESD Safety before logging practice.',cost:'PLAN BEFORE YOU BUY'},
 drawing:{name:'Drawing',nodeId:'drw-start',description:'One deliberate line is a start.',minutes:10,need:['Any pencil','Any paper you already own'],action:'Make one line you meant to make, then fill the rest of the page with long strokes drawn in one movement.',safety:'Keep the wrist neutral, draw from the shoulder, and take a short break every twenty minutes.',cost:'USE WHAT YOU OWN'},
 painting:{name:'Painting',nodeId:'pnt-start',description:'Mix it before you buy it.',minutes:20,need:['A red, a blue, a yellow and a white','One brush and any sealed surface'],action:'Mix a ten-step scale from white to your darkest mix and note what went into each.',safety:'Start with acrylic or watercolour. Keep air moving, keep brushes out of your mouth, and never pour solvent down a drain. Complete Ventilation and Materials Safety before logging practice.',cost:'A FEW SUPPLIES NEEDED'},
 running:{name:'Running',nodeId:'run-start',description:'Slower than you think.',minutes:20,need:['Comfortable trainers you already own','A flat, well-lit route'],action:'Walk five minutes, then alternate one minute easy running with two minutes walking.',safety:'Build up gradually, run facing traffic where there is no path, wear something reflective in low light, and stop on new sharp pain. Complete Load, Traffic and Heat before logging practice.',cost:'USE WHAT YOU OWN'},
 volleyball:{name:'Volleyball',nodeId:'vol-start',description:'Turn up; the rest is three touches.',minutes:20,need:['Clean non-marking indoor shoes','A local open session'],action:'Warm up the shoulders and ankles, then make fifty controlled forearm passes against a wall.',safety:'Warm up before hitting, set with firm fingers, land on two feet, and call loudly for every ball. Complete Warm-Up, Fingers and Ankles before logging practice.',cost:'MOSTLY BORROWED'},
 reading:{name:'Reading',nodeId:'rdg-start',description:'A few pages, most days.',minutes:10,need:['One book you actually want to read','A library card, if you need one'],action:'Read for ten minutes at a time you already do something predictable.',safety:'Light on the page rather than behind it, book near eye level, and look at something distant every twenty minutes.',cost:'FREE WITH A LIBRARY CARD'}
} as const;
export type QuickHobby=HobbyId;
/** A hobby without a first quest is a type error rather than a blank quick-start panel. */
const _everyHobbyHasAFirstQuest:Record<HobbyId,unknown>=firstQuests;void _everyHobbyHasAFirstQuest;
