import {writeFileSync} from 'node:fs';
import {hobbies,nodes,gear,avatarItems,achievements,quests} from '../lib/content';
const quote=(v:unknown)=>`'${JSON.stringify(v).replaceAll("'","''")}'::jsonb`;
const text=(v:string)=>`'${v.replaceAll("'","''")}'`;
const sql:string[]=['-- Generated from canonical TypeScript / JSON seed content.','begin;'];
for(const h of hobbies)sql.push(`insert into public.hobbies(slug,name,content) values(${text(h.id)},${text(h.name)},${quote(h)}) on conflict(slug) do update set content=excluded.content;`);
for(const n of nodes)sql.push(`insert into public.skill_nodes(hobby_id,slug,title,content) values((select id from public.hobbies where slug=${text(n.hobbyId)}),${text(n.id)},${text(n.title)},${quote(n)}) on conflict(slug) do update set content=excluded.content;`);
for(const n of nodes){for(const p of n.requires)sql.push(`insert into public.node_prerequisites(node_id,prerequisite_node_id) values((select id from public.skill_nodes where slug=${text(n.id)}),(select id from public.skill_nodes where slug=${text(p)})) on conflict do nothing;`);for(const [i,g]of n.orGroups.entries())for(const p of g)sql.push(`insert into public.node_prerequisites(node_id,prerequisite_node_id,group_key,requirement_type) values((select id from public.skill_nodes where slug=${text(n.id)}),(select id from public.skill_nodes where slug=${text(p)}),'or-${i}','any') on conflict do nothing;`);}
for(const g of gear)sql.push(`insert into public.gear_items(slug,hobby_id,content) values(${text(g.id)},(select id from public.hobbies where slug=${text(g.hobbyId)}),${quote(g)}) on conflict(slug) do update set content=excluded.content;`);
for(const [table,items] of [['avatar_items',avatarItems],['achievements',achievements],['quest_templates',quests]] as const)for(const i of items)sql.push(`insert into public.${table}(slug,content) values(${text(i.id)},${quote(i)}) on conflict(slug) do update set content=excluded.content;`);
for(const h of hobbies){const resource=nodes.find(n=>n.hobbyId===h.id)!.resources[0];sql.push(`insert into public.resources(slug,content) values(${text(h.id+'-reference')},${quote(resource)}) on conflict(slug) do update set content=excluded.content;`);}
for(const n of nodes){sql.push(`insert into public.node_resources(node_id,resource_id) values((select id from public.skill_nodes where slug=${text(n.id)}),(select id from public.resources where slug=${text(n.hobbyId+'-reference')})) on conflict do nothing;`);for(const g of gear.filter(g=>g.hobbyId===n.hobbyId&&g.necessity==='required'))sql.push(`insert into public.node_gear_requirements(node_id,gear_item_id,requirement) values((select id from public.skill_nodes where slug=${text(n.id)}),(select id from public.gear_items where slug=${text(g.id)}),'required') on conflict do nothing;`);}
sql.push('commit;');writeFileSync('supabase/seed.sql',sql.join('\n')+'\n');console.log('Wrote supabase/seed.sql');
